import type { AppConfig } from "../config";
import type { Bounty, LedgerData } from "../types";
export const config: AppConfig = {
  chainId: "juno-1",
  contract: "juno1jmngxh7kdelch3v5xu02ze2gup887v55csqns4qmxeskgy2ldl5qj494qw",
  rpc: "https://rpc.example",
  explorer: "https://www.mintscan.io/juno",
  codeId: 5150,
  codeChecksum:
    "f05e9eaf3f90c7a5273bea3e8db8ff570b4f9192a4032472865cd4293b49bce1",
};
export const bounty: Bounty = {
  id: 1,
  creator: "juno1creatorxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  terms: {
    title: "Fund public goods tooling",
    summary: "A real bounty record",
    acceptance_criteria: "Ship it",
    content_uri: null,
    content_digest: null,
    config_version: 1,
    ratification_seconds: 259200,
    max_bounty_total: "100000000",
    max_contributors: 20,
    max_rounds: 3,
    max_evidence_uri_bytes: 512,
    max_rationale_bytes: 1000,
    max_reason_bytes: 500,
  },
  project_candidate: null,
  status: "open",
  refund_reason: null,
  total_contribution: "2500000",
  contributor_count: 1,
  next_round: 1,
  active_round: null,
  paid_recipient: null,
  paid_amount: "0",
  refunded_amount: "0",
  paid_at: null,
  graduated_at: null,
  created_at: "1700000000",
  expires_at: "1800000000",
  history_count: 1,
};
export const ledger: LedgerData = {
  config: {
    native_denom: "ujuno",
    governor: "juno1gov",
    agent: "juno1agent",
    registry: "juno1registry",
    ratification_seconds: 259200,
    min_contribution: "1000000",
    max_bounty_total: "100000000",
    min_lifetime_seconds: 86400,
    max_lifetime_seconds: 31536000,
    max_contributors: 20,
    max_rounds: 3,
    limits: {
      max_title_bytes: 100,
      max_summary_bytes: 500,
      max_acceptance_criteria_bytes: 1000,
      max_uri_bytes: 512,
      max_rationale_bytes: 1000,
      max_reason_bytes: 500,
      max_page_limit: 50,
    },
    version: 1,
  },
  pause: { paused: false, reason: null, actor: null, changed_at: null },
  health: {
    accounting: {
      active_escrow: "2500000",
      outstanding_refunds: "0",
      pending_payout_liabilities: "0",
      lifetime_received: "2500000",
      lifetime_paid: "0",
      lifetime_refunded: "0",
    },
    actual_native_balance: "2500000",
    liabilities: "2500000",
    fully_backed: true,
  },
  bounties: [bounty],
  observationHeight: 123456,
  refreshedAt: new Date(),
  weakConsistency: true,
};
