import type { AppConfig } from './config';
import type { Attestation, BondTotals, ContractConfig, DetailData, Evidence, LedgerData, Page, RankedPage, Request, RequestAction, Status, StatusHistory } from './types';

export const PAGE_LIMIT = 50;
export const STATUS_CODES: Record<Status, number> = { open: 1, qualified: 2, not_prioritized: 3, duplicate: 4, spam: 5, building: 6, review: 7, blocked: 8, archived: 9, shipped: 10 };
export const queries = {
  config: () => ({ config: {} }), bondTotals: () => ({ bond_totals: {} }),
  requests: (startAfter: number | null = null) => ({ requests: { status: null, category: null, author: null, start_after_id: startAfter, limit: PAGE_LIMIT } }),
  rankedRequests: (status: number, cursor: string | null = null) => ({ ranked_requests: { status, category: null, cursor, limit: PAGE_LIMIT } }),
  request: (id: number) => ({ request: { id } }),
  evidence: (requestId: number, startAfter: number | null = null) => ({ evidence: { request_id: requestId, start_after_id: startAfter, limit: PAGE_LIMIT } }),
  statusHistory: (requestId: number, startAfter: number | null = null) => ({ status_history: { request_id: requestId, start_after_id: startAfter, limit: PAGE_LIMIT } }),
  requestActions: (requestId: number, startAfter: number | null = null) => ({ request_actions: { request_id: requestId, start_after_id: startAfter, limit: PAGE_LIMIT } }),
  shipmentAttestation: (requestId: number) => ({ shipment_attestation: { request_id: requestId } }),
} as const;

interface RpcClient { queryContractSmart(address: string, query: object): Promise<unknown>; getChainId(): Promise<string>; getHeight(): Promise<number>; getContract(address: string): Promise<{ address: string; codeId: number }>; getCodeDetails(codeId: number): Promise<{ checksum: string }>; disconnect(): void }
type Connect = (rpc: string) => Promise<RpcClient>;
const connect: Connect = async (rpc) => { const { CosmWasmClient } = await import('@cosmjs/cosmwasm-stargate'); return CosmWasmClient.connect(rpc); };
const statuses = new Set<Status>(Object.keys(STATUS_CODES) as Status[]);
function record(value: unknown, context: string): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error(`Malformed ${context} response from RPC.`); return value as Record<string, unknown>; }
function text(value: unknown, context: string): string { if (typeof value !== 'string') throw new Error(`Malformed ${context} response from RPC.`); return value; }
function integer(value: unknown, context: string): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) throw new Error(`Malformed ${context} response from RPC.`); return value; }
function uint(value: unknown, context: string): string { const item = text(value, context); if (!/^\d+$/.test(item) || BigInt(item) > 18_446_744_073_709_551_615n) throw new Error(`Malformed ${context} response from RPC.`); return item; }
function nullableText(value: unknown, context: string): string | null { return value === null ? null : text(value, context); }
function field(value: unknown, name: string, context: string): unknown { const item = record(value, context); if (!(name in item)) throw new Error(`Malformed ${context} response from RPC.`); return item[name]; }
function rawPage(value: unknown, context: string): Page<unknown> { const item = record(value, context); if (!Array.isArray(item.items)) throw new Error(`Malformed ${context} response from RPC.`); const next = item.next_start_after; if (next !== null && (typeof next !== 'number' || !Number.isSafeInteger(next))) throw new Error(`Malformed ${context} cursor from RPC.`); return { items: item.items, next_start_after: next as number | null, query_height: integer(item.query_height, context) }; }
function assertStatus(value: unknown, context: string): Status { const status = text(value, context) as Status; if (!statuses.has(status)) throw new Error(`Malformed ${context} response from RPC.`); return status; }
function assertNumberArray(value: unknown, context: string): number[] { if (!Array.isArray(value)) throw new Error(`Malformed ${context} response from RPC.`); return value.map((item) => integer(item, context)); }
function assertRequest(value: unknown): Request { const x = record(value, 'request'); const bond = record(x.bond, 'request bond');
  integer(x.id,'request'); text(x.author,'request'); text(x.title,'request'); text(x.summary,'request'); text(x.acceptance_criteria,'request'); text(x.category,'request'); nullableText(x.detail_uri,'request'); nullableText(x.detail_digest,'request');
  integer(x.snapshot_height,'request'); uint(x.total_power,'request'); integer(x.opened_height,'request'); integer(x.closes_height,'request'); integer(x.quorum_bps,'request'); integer(x.support_bps,'request'); integer(x.work_inactivity_blocks,'request'); integer(x.evidence_policy_version,'request');
  assertStatus(x.status,'request'); uint(x.support_power,'request'); uint(x.oppose_power,'request'); integer(x.voter_count,'request'); uint(bond.amount,'request bond'); text(bond.state,'request bond'); integer(x.work_round,'request'); uint(x.created_at,'request'); uint(x.updated_at,'request');
  return x as unknown as Request; }
function assertConfig(value: unknown): ContractConfig { const x=record(value,'config'); text(x.governor,'config'); text(x.steward,'config'); text(x.verifier,'config'); text(x.native_denom,'config'); uint(x.submission_bond,'config'); integer(x.voting_period_blocks,'config'); integer(x.evidence_policy_version,'config'); if(typeof x.submissions_paused!=='boolean') throw new Error('Malformed config response from RPC.'); return x as unknown as ContractConfig; }
function assertBonds(value: unknown): BondTotals { const x=record(value,'bond totals'); uint(x.locked,'bond totals'); uint(x.refundable,'bond totals'); uint(x.forfeited,'bond totals'); return x as unknown as BondTotals; }
function assertEvidence(value: unknown): Evidence { const x=record(value,'evidence'); integer(x.id,'evidence'); integer(x.request_id,'evidence'); text(x.submitter,'evidence'); text(x.kind,'evidence'); text(x.uri,'evidence'); text(x.digest,'evidence'); text(x.note,'evidence'); integer(x.work_round,'evidence'); uint(x.submitted_at,'evidence'); integer(x.submitted_height,'evidence'); return x as unknown as Evidence; }
function assertHistory(value: unknown): StatusHistory { const x=record(value,'status history'); integer(x.id,'status history'); integer(x.request_id,'status history'); text(x.actor,'status history'); assertStatus(x.from,'status history'); assertStatus(x.to,'status history'); nullableText(x.reason,'status history'); assertNumberArray(x.evidence_ids,'status history'); integer(x.height,'status history'); uint(x.timestamp,'status history'); return x as unknown as StatusHistory; }
function assertAction(value: unknown): RequestAction { const x=record(value,'request action'); integer(x.id,'request action'); integer(x.request_id,'request action'); text(x.actor,'request action'); if(typeof x.action!=='string') record(x.action,'request action'); nullableText(x.reason,'request action'); integer(x.height,'request action'); uint(x.timestamp,'request action'); return x as unknown as RequestAction; }
function assertAttestation(value: unknown): Attestation | null { if(value===null) return null; const x=record(value,'shipment attestation'); text(x.verifier,'shipment attestation'); text(x.rationale,'shipment attestation'); assertNumberArray(x.evidence_ids,'shipment attestation'); integer(x.work_round,'shipment attestation'); uint(x.submitted_at,'shipment attestation'); integer(x.submitted_height,'shipment attestation'); return x as unknown as Attestation; }
async function verifyDeployment(client: RpcClient, config: AppConfig): Promise<void> { const [chainId, contract] = await Promise.all([client.getChainId(), client.getContract(config.contract)]); if(chainId!==config.chainId) throw new Error(`Deployment mismatch: expected chain ${config.chainId}, observed ${chainId}.`); if(contract.address!==config.contract||contract.codeId!==config.codeId) throw new Error(`Deployment mismatch: expected contract ${config.contract} at Code ID ${config.codeId}.`); const code=await client.getCodeDetails(config.codeId); if(code.checksum.toLowerCase()!==config.codeChecksum) throw new Error('Deployment mismatch: contract code checksum is not the verified artifact.'); }
async function collectIdPages<T>(query: (message: object)=>Promise<unknown>, build:(cursor:number|null)=>object, validate:(value:unknown)=>T, context:string):Promise<{items:T[];queryHeight:number}>{ const items:T[]=[]; let cursor:number|null=null; let height=Number.MAX_SAFE_INTEGER; const seen=new Set<number>(); for(let i=0;i<1000;i++){ const p=rawPage(await query(build(cursor)),context); height=Math.min(height,p.query_height); items.push(...p.items.map(validate)); if(p.next_start_after===null) return {items,queryHeight:height}; if(seen.has(p.next_start_after)) throw new Error(`Repeated ${context} cursor from RPC.`); seen.add(p.next_start_after); cursor=p.next_start_after; } throw new Error(`Too many ${context} pages from RPC.`); }
async function collectRanked(query:(message:object)=>Promise<unknown>, status:Status):Promise<{items:Request[];queryHeight:number}>{ const items:Request[]=[]; let cursor:string|null=null; let height=Number.MAX_SAFE_INTEGER; const seen=new Set<string>(); for(let i=0;i<1000;i++){ const p=mapRankedResponse(await query(queries.rankedRequests(STATUS_CODES[status],cursor))); height=Math.min(height,p.query_height); items.push(...p.items); if(p.next_cursor===null) return {items,queryHeight:height}; if(seen.has(p.next_cursor)) throw new Error('Repeated ranked cursor from RPC.'); seen.add(p.next_cursor); cursor=p.next_cursor; } throw new Error('Too many ranked request pages from RPC.'); }
async function verifyProtocolConfig(query:(message:object)=>Promise<unknown>):Promise<ContractConfig>{ const config=assertConfig(field(await query(queries.config()),'config','config')); if(config.native_denom!=='ujunox'||config.evidence_policy_version!==1) throw new Error('Deployment mismatch: unsupported contract configuration.'); return config; }
export interface VoiceDataSource { loadLedger(): Promise<LedgerData>; loadDetail(id:number):Promise<DetailData> }
export function createDataSource(config:AppConfig,connector:Connect=connect):VoiceDataSource { const queryWith=(client:RpcClient)=>(message:object)=>client.queryContractSmart(config.contract,message); return {
  async loadLedger(){ const client=await connector(config.rpc); try { await verifyDeployment(client,config); const query=queryWith(client); const statusList=Object.keys(STATUS_CODES) as Status[]; const [contractConfig,bondsRaw,all,rpcHeight,...rankedPages]=await Promise.all([verifyProtocolConfig(query),query(queries.bondTotals()),collectIdPages(query,queries.requests,assertRequest,'requests'),client.getHeight(),...statusList.map((status)=>collectRanked(query,status))]); const ranked=Object.fromEntries(statusList.map((status,index)=>[status,rankedPages[index].items])) as Record<Status,Request[]>; return {config:contractConfig,bonds:assertBonds(field(bondsRaw,'totals','bond totals')),requests:all.items,ranked,queryHeight:Math.min(rpcHeight,all.queryHeight,...rankedPages.map((p)=>p.queryHeight)),refreshedAt:new Date(),weakConsistency:true}; } finally {client.disconnect();} },
  async loadDetail(id){ if(!Number.isSafeInteger(id)||id<1) throw new Error('Invalid request ID.'); const client=await connector(config.rpc); try { await verifyDeployment(client,config); const query=queryWith(client); await verifyProtocolConfig(query); const [requestRaw,rpcHeight]=await Promise.all([query(queries.request(id)),client.getHeight()]); const request=assertRequest(field(requestRaw,'request','request')); if(request.evidence_policy_version!==1) throw new Error('Deployment mismatch: request evidence policy is unsupported.'); const jobs=[collectIdPages(query,(c)=>queries.evidence(id,c),assertEvidence,'evidence'),collectIdPages(query,(c)=>queries.statusHistory(id,c),assertHistory,'status history'),collectIdPages(query,(c)=>queries.requestActions(id,c),assertAction,'request actions'),query(queries.shipmentAttestation(id))] as const; const [er,hr,ar,tr]=await Promise.allSettled(jobs); const sectionErrors:NonNullable<DetailData['sectionErrors']>={}; const message=(r:unknown)=>r instanceof Error?r.message:'RPC query failed.'; const child=<T>(r:PromiseSettledResult<{items:T[];queryHeight:number}>,key:keyof typeof sectionErrors)=>{if(r.status==='fulfilled')return r.value;sectionErrors[key]=message(r.reason);return {items:[],queryHeight:rpcHeight};}; const evidence=child(er,'evidence'),history=child(hr,'history'),actions=child(ar,'actions'); let attestation:Attestation|null=null; if(tr.status==='fulfilled'){try{attestation=assertAttestation(field(tr.value,'attestation','shipment attestation'));}catch(error){sectionErrors.attestation=message(error);}}else sectionErrors.attestation=message(tr.reason); return {request,evidence:evidence.items,history:history.items,actions:actions.items,attestation,queryHeight:Math.min(rpcHeight,evidence.queryHeight,history.queryHeight,actions.queryHeight),sectionErrors}; } finally {client.disconnect();} }
}; }
export function mapRequestResponse(value: unknown): Request { return assertRequest(field(value, 'request', 'request')); }
export function mapRankedResponse(value:unknown):RankedPage { const x=record(value,'ranked requests'); if(!Array.isArray(x.items)||typeof x.query_height!=='number') throw new Error('Malformed ranked requests response from RPC.'); const cursor=x.next_cursor; if(cursor!==null&&typeof cursor!=='string') throw new Error('Malformed ranked cursor from RPC.'); return {items:x.items.map(assertRequest),next_cursor:cursor as string|null,query_height:integer(x.query_height,'ranked requests')}; }
