import { useMemo } from 'react';
import type { VoiceDataSource } from './client';
import { actionLabel, compactAddress, formatPower, formatTimestamp, netPower, statusLabels } from './format';
import type { AppConfig } from './config';
import { useAsync } from './useAsync';
import { safeUri } from './uri';

export function Detail({ source, config, id, onBack }: { source: VoiceDataSource; config: AppConfig; id: number; onBack: () => void }) {
  const load = useMemo(() => () => source.loadDetail(id), [source, id]);
  const [state, retry] = useAsync(load, id);
  if (state.kind === 'loading') return <main><ViewState title={`Receiving request ${id}…`} /></main>;
  if (state.kind === 'error') return <main><button className="back" onClick={onBack}>← Signal ledger</button><ViewState title="Request unavailable" detail={state.message}><button className="button primary" onClick={retry}>Retry query</button></ViewState></main>;
  const { request, evidence, history, actions, attestation, sectionErrors = {} } = state.data;
  const detailUri = request.detail_uri ? safeUri(request.detail_uri) : null;
  const net = netPower(request);
  return <main><button className="back" onClick={onBack}>← Signal ledger</button>
    <div className="detail-heading"><div><p className="eyebrow">VOICE-{String(id).padStart(3, '0')} · {request.category} · {statusLabels[request.status]}</p><h1>{request.title}</h1><p>{request.summary}</p></div><aside className="facts"><div className="fact"><span>TESTNET</span><strong>{config.chainId}</strong></div><div className="fact"><span>CONTRACT</span><strong><a href={`${config.explorer}/address/${encodeURIComponent(config.contract)}`} target="_blank" rel="noopener noreferrer">{compactAddress(config.contract)}</a></strong></div><div className="fact"><span>Query height</span><strong>{state.data.queryHeight.toLocaleString()}</strong></div></aside></div>
    <div className="detail-grid"><article className="panel"><h2>Immutable request</h2><dl className="metadata"><dt>Author</dt><dd title={request.author}>{compactAddress(request.author)}</dd><dt>Opened / closes</dt><dd>{request.opened_height.toLocaleString()} / {request.closes_height.toLocaleString()}</dd><dt>Created</dt><dd><ChainTime value={request.created_at} /></dd><dt>Detail reference</dt><dd>{request.detail_uri ? detailUri ? <a href={detailUri.href} rel="noopener noreferrer" target="_blank">{detailUri.label} {detailUri.kind === 'ipfs' && '(IPFS gateway)'}</a> : <span title="Unsafe URI scheme is never linked">{request.detail_uri} (not linked)</span> : 'None'}</dd><dt>Detail digest</dt><dd className="break">{request.detail_digest ?? 'None'}</dd></dl><h2>Acceptance criteria</h2><div className="acceptance">{request.acceptance_criteria}</div>
      <h2>Status history</h2>{sectionErrors.history && <SectionError section="status history" message={sectionErrors.history} />}{history.length ? <ol className="timeline">{history.map((event) => <li key={event.id}><strong>{statusLabels[event.from]} → {statusLabels[event.to]}</strong><span>Height {event.height.toLocaleString()} · {compactAddress(event.actor)} · <ChainTime value={event.timestamp} /></span><p>{event.reason ?? 'No reason recorded.'}</p></li>)}</ol> : <Empty text="No status transitions recorded." />}
      <h2>Request actions</h2>{sectionErrors.actions && <SectionError section="request actions" message={sectionErrors.actions} />}{actions.length ? <ol className="timeline">{actions.map((item) => <li key={item.id}><strong>{actionLabel(item.action)}</strong><span>Height {item.height.toLocaleString()} · {compactAddress(item.actor)} · <ChainTime value={item.timestamp} /></span><p>{item.reason ?? 'No reason recorded.'}</p></li>)}</ol> : <Empty text="No request actions recorded." />}
    </article><aside className="panel"><h2>Snapshot & tally</h2><div className="metrics"><Metric label="Support" value={formatPower(request.support_power)} accent /><Metric label="Oppose" value={formatPower(request.oppose_power)} /><Metric label="Net" value={`${net >= 0 ? '+' : ''}${formatPower(net.toString())}`} /><Metric label="Voters" value={request.voter_count.toLocaleString()} /><Metric label="Snapshot" value={request.snapshot_height.toLocaleString()} /><Metric label="Total power" value={formatPower(request.total_power)} /></div>
      <h2>Bond</h2><p><span className="badge">{request.bond.state}</span> {formatPower(request.bond.amount)} {request.bond.amount === '1' ? '' : 'units'}</p>
      <h2>Evidence</h2>{sectionErrors.evidence && <SectionError section="evidence" message={sectionErrors.evidence} />}{evidence.length ? evidence.map((item) => { const uri = safeUri(item.uri); return <section className="evidence" key={item.id}><strong>{item.kind.replaceAll('_', ' ')}</strong><p>{uri ? <a href={uri.href} target="_blank" rel="noopener noreferrer">{item.uri}</a> : <span>{item.uri} (not linked)</span>}</p><p>{item.note}</p><code>{item.digest}</code><small>By {compactAddress(item.submitter)} · height {item.submitted_height.toLocaleString()} · <ChainTime value={item.submitted_at} /></small></section>; }) : <Empty text="No evidence attached." />}
      <h2>Shipment attestation</h2>{sectionErrors.attestation && <SectionError section="shipment attestation" message={sectionErrors.attestation} />}{attestation ? <section className="attestation"><strong>Verified by {compactAddress(attestation.verifier)}</strong><p>{attestation.rationale}</p><small>Evidence IDs: {attestation.evidence_ids.join(', ') || 'None'} · height {attestation.submitted_height.toLocaleString()} · <ChainTime value={attestation.submitted_at} /></small></section> : <Empty text="No shipment attestation recorded." />}
      <div className="later"><strong>Read-only foundation</strong><p>Wallet transactions and signing arrive in a later slice.</p></div></aside></div>
  </main>;
}
function ChainTime({ value }: { value: string }) { const date = new Date(Number(BigInt(value) / 1_000_000n)); return <time dateTime={date.toISOString()}>{formatTimestamp(value)}</time>; }
function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`metric ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function SectionError({ section, message }: { section: string; message: string }) { return <p className="section-error" role="status">Could not load {section}: {message}</p>; }
function ViewState({ title, detail, children }: { title: string; detail?: string; children?: React.ReactNode }) { return <div className="state" role="status"><h1>{title}</h1>{detail && <p>{detail}</p>}{children}</div>; }
