import { useMemo } from 'react';
import type { VoiceDataSource } from './client';
import { actionLabel, compactAddress, formatJuno, formatTimestamp, netPower, statusLabels } from './format';
import type { AppConfig } from './config';
import { useAsync } from './useAsync';
import { safeUri } from './uri';
import type { PublicTransactions, TransactionReceipt } from './wallet';
import { RequestActions } from './WalletActions';

export function Detail({ source, config, id, onBack, account=null, transactions, onSuccess=()=>undefined, refreshToken=0 }: { source: VoiceDataSource; config: AppConfig; id: number; onBack: () => void; account?:string|null; transactions?:PublicTransactions; onSuccess?:(receipt:TransactionReceipt)=>void; refreshToken?:number }) {
  const load = useMemo(() => { void refreshToken; return () => source.loadDetail(id); }, [source, id, refreshToken]);
  const [state, retry] = useAsync(load, id);
  if (state.kind === 'loading') return <main><ViewState title={`Receiving request ${id}…`} /></main>;
  if (state.kind === 'error') return <main><button className="back" onClick={onBack}>← Signal ledger</button><ViewState title="Request unavailable" detail={state.message}><button className="button primary" onClick={retry}>Retry query</button></ViewState></main>;
  const { request, evidence, history, actions, attestation, sectionErrors = {} } = state.data;
  const detailUri = request.detail_uri ? safeUri(request.detail_uri) : null;
  const net = netPower(request);
  return <main className="detail-page"><button className="back" onClick={onBack}>← Signal ledger</button>
    <header className="detail-heading"><p className="eyebrow">VOICE-{String(id).padStart(3, '0')} · #{request.category}</p><div className="detail-title"><h1>{request.title}</h1><span className="badge">{statusLabels[request.status]}</span></div><p>{request.summary}</p></header>
    <div className="detail-grid"><article className="panel request-body"><h2>Acceptance criteria</h2><div className="acceptance">{request.acceptance_criteria}</div>
      <details className="request-facts"><summary>On-chain request details</summary><dl className="metadata"><dt>Author</dt><dd title={request.author}>{compactAddress(request.author)}</dd><dt>Created</dt><dd><ChainTime value={request.created_at} /></dd><dt>Opened / closes</dt><dd>{request.opened_height.toLocaleString()} / {request.closes_height.toLocaleString()}</dd><dt>Contract</dt><dd><a href={`${config.explorer}/address/${encodeURIComponent(config.contract)}`} target="_blank" rel="noopener noreferrer">{compactAddress(config.contract)}</a></dd><dt>Query height</dt><dd>{state.data.queryHeight.toLocaleString()}</dd><dt>Detail reference</dt><dd>{request.detail_uri ? detailUri ? <a href={detailUri.href} rel="noopener noreferrer" target="_blank">{detailUri.label} {detailUri.kind === 'ipfs' && '(IPFS gateway)'}</a> : <span title="Unsafe URI scheme is never linked">{request.detail_uri} (not linked)</span> : 'None'}</dd><dt>Detail digest</dt><dd className="break">{request.detail_digest ?? 'None'}</dd></dl></details>
      <h2>Activity</h2>{sectionErrors.history && <SectionError section="status history" message={sectionErrors.history} />}{history.length ? <ol className="timeline">{history.map((event) => <li key={event.id}><strong>{statusLabels[event.from]} → {statusLabels[event.to]}</strong><span>Height {event.height.toLocaleString()} · {compactAddress(event.actor)} · <ChainTime value={event.timestamp} /></span><p>{event.reason ?? 'No reason recorded.'}</p></li>)}</ol> : <Empty text="No status transitions recorded." />}
      <details className="protocol-log" open={Boolean(sectionErrors.actions)}><summary>Protocol action log ({actions.length})</summary>{sectionErrors.actions && <SectionError section="request actions" message={sectionErrors.actions} />}{actions.length ? <ol className="timeline">{actions.map((item) => <li key={item.id}><strong>{actionLabel(item.action)}</strong><span>Height {item.height.toLocaleString()} · {compactAddress(item.actor)} · <ChainTime value={item.timestamp} /></span><p>{item.reason ?? 'No reason recorded.'}</p></li>)}</ol> : <Empty text="No request actions recorded." />}</details>
    </article><aside className="detail-rail"><section className="panel signal-panel"><h2>Signal</h2><div className="metrics"><Metric label="Support" value={formatJuno(request.support_power)} accent /><Metric label="Oppose" value={formatJuno(request.oppose_power)} /><Metric label="Net" value={formatJuno(net, { showPositiveSign: true })} /><Metric label="Voters" value={request.voter_count.toLocaleString()} /></div><details className="snapshot-details"><summary>Snapshot and bond</summary><dl className="metadata compact"><dt>Snapshot height</dt><dd>{request.snapshot_height.toLocaleString()}</dd><dt>Total power</dt><dd>{formatJuno(request.total_power)}</dd><dt>Bond</dt><dd><span className="badge">{request.bond.state}</span> {formatJuno(request.bond.amount)}</dd></dl></details></section>
      <section className="panel evidence-panel"><h2>Evidence</h2>{sectionErrors.evidence && <SectionError section="evidence" message={sectionErrors.evidence} />}{evidence.length ? evidence.map((item) => { const uri = safeUri(item.uri); return <section className="evidence" key={item.id}><strong>{item.kind.replaceAll('_', ' ')}</strong><p>{uri ? <a href={uri.href} target="_blank" rel="noopener noreferrer">{item.uri}</a> : <span>{item.uri} (not linked)</span>}</p><p>{item.note}</p><code>{item.digest}</code><small>By {compactAddress(item.submitter)} · height {item.submitted_height.toLocaleString()} · <ChainTime value={item.submitted_at} /></small></section>; }) : <Empty text="No evidence attached." />}
      <h2>Shipment attestation</h2>{sectionErrors.attestation && <SectionError section="shipment attestation" message={sectionErrors.attestation} />}{attestation ? <section className="attestation"><strong>Verified by {compactAddress(attestation.verifier)}</strong><p>{attestation.rationale}</p><small>Evidence IDs: {attestation.evidence_ids.join(', ') || 'None'} · height {attestation.submitted_height.toLocaleString()} · <ChainTime value={attestation.submitted_at} /></small></section> : <Empty text="No shipment attestation recorded." />}</section>
      {transactions?<RequestActions request={request} account={account} transactions={transactions} onSuccess={onSuccess}/>:<div className="later"><strong>Read-only test harness</strong><p>Wallet transactions and signing require the public transaction service.</p></div>}</aside></div>
  </main>;
}
function ChainTime({ value }: { value: string }) { const date = new Date(Number(BigInt(value) / 1_000_000n)); return <time dateTime={date.toISOString()}>{formatTimestamp(value)}</time>; }
function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`metric ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function SectionError({ section, message }: { section: string; message: string }) { return <p className="section-error" role="status">Could not load {section}: {message}</p>; }
function ViewState({ title, detail, children }: { title: string; detail?: string; children?: React.ReactNode }) { return <div className="state" role="status"><h1>{title}</h1>{detail && <p>{detail}</p>}{children}</div>; }
