import { useMemo, useState } from "react";
import type { AppConfig } from "./config";
import type { Epoch, GaugeData, GaugeDataSource } from "./gauge";
import { buildGaugeIntent, gaugeEligibility, type GaugeAction, type GaugeTransactionFlow, type PreferenceInput } from "./gaugeActions";
import type { TransactionOutcome, TransactionReview } from "./transactions";
import { useAsync } from "./useAsync";

const compact = (value: string) => value.length > 24 ? `${value.slice(0, 12)}…${value.slice(-6)}` : value;
const utc = (seconds: number) => new Date(seconds * 1000).toISOString();
const juno = (amount: string) => { const value = BigInt(amount), whole = value / 1_000_000n, fraction = (value % 1_000_000n).toString().padStart(6, "0").replace(/0+$/, ""); return `${whole.toLocaleString()}${fraction ? `.${fraction}` : ""} JUNO`; };
const percent = (part: string, total: string) => BigInt(total) === 0n ? "0.00%" : `${(BigInt(part) * 10_000n / BigInt(total) / 100n).toString()}.${(BigInt(part) * 10_000n / BigInt(total) % 100n).toString().padStart(2, "0")}%`;
const outcome = (epoch: Epoch) => epoch.outcome === "open" ? "Voting open" : epoch.outcome === "distributed" ? `Distributed · ${epoch.messageCount} message${epoch.messageCount === 1 ? "" : "s"}` : epoch.outcome === "no_distribution_turnout" ? "No distribution · turnout" : "No distribution · no eligible options";

export function GaugeVoting({ source, config, transactionFlow, sender }: { source: GaugeDataSource; config: AppConfig; transactionFlow?: GaugeTransactionFlow; sender?: string }) {
  const [connected, setConnected] = useState<string | null>(sender ?? null), activeSender = sender ?? connected;
  const load = useMemo(() => () => source.loadGauge(activeSender ?? undefined), [source, activeSender]);
  const [state, retry] = useAsync(load, `gauge ${activeSender ?? "public"}`);
  const [selectedEpoch, setSelectedEpoch] = useState<number | null>(null);
  if (state.kind === "loading") return <main><State title="Loading gauge state…" detail="Verifying the gauge, voting module, Program Vault, registry, fixed epochs, and chain time." /></main>;
  if (state.kind === "error") return <main><State title="Gauge unavailable" detail={state.message}><button className="button" onClick={retry}>Retry gauge query</button></State></main>;
  const data = state.data, selected = data.epochs.find((epoch) => epoch.epochId === selectedEpoch) ?? data.current ?? data.previous;
  return <main>
    <section className="hero gauge-hero" aria-labelledby="gauge-title"><div><p className="eyebrow">HACK JUNO · EPOCH GAUGE</p><h1 id="gauge-title">Weighted allocation</h1><p>Inspect fixed historical epochs and direct a funded allocation with Juno stake held at the epoch snapshot. Every write is reconstructed from canonical chain state before wallet review and again before signing.</p></div><aside className="hero-summary" aria-label="Gauge summary"><Fact label="Gauge" value="#0" /><Fact label="State" value={data.gauge.isStopped ? "Stopped" : data.current?.outcome === "open" ? "Epoch open" : "Ready"} /><Fact label="Vault" value={juno(data.vaultBalance)} /></aside></section>
    {(data.gauge.isStopped || data.adapterStopped) && <section className="notice danger" role="alert"><strong>Distribution is stopped.</strong> Voting, opening, and execution remain disabled while {data.gauge.isStopped ? "the gauge stop" : "the registry adapter stop"} is active.</section>}
    <section className="option-note"><strong>Retained value is explicit.</strong><p><code>do-not-distribute</code> intentionally keeps its share in the Program Vault. Unused preference weight, capped or unselected power, ineligible projects, failed turnout, and no-eligible-option outcomes also stay in the Vault. Nothing shown here implies automatic rollover into another epoch.</p></section>
    <section className="epoch-index" aria-labelledby="epoch-history"><div className="toolbar"><div><p className="eyebrow">CANONICAL HISTORY</p><h2 id="epoch-history">Current and previous epochs</h2></div>{data.epochs.length > 0 && <label className="control-label">Epoch detail<select value={selected?.epochId ?? ""} onChange={(event) => setSelectedEpoch(Number(event.target.value))}>{[...data.epochs].reverse().map((epoch) => <option key={epoch.epochId} value={epoch.epochId}>Epoch {epoch.epochId} · {outcome(epoch)}</option>)}</select></label>}</div>
      {!selected ? <State title="No epoch has opened" detail="The verified mainnet gauge has no historical epoch. A public open is shown only when canonical time, funding, and stop state permit it." /> : <EpochDetail epoch={selected} data={data} />}
    </section>
    <GaugeWorkbench key={`${data.current?.epochId ?? "none"}:${data.ballot?.revisedAt ?? "none"}`} data={data} source={source} config={config} transactionFlow={transactionFlow} activeSender={activeSender} setConnected={setConnected} />
    <details className="network-details"><summary>Gauge provenance <span>Direct RPC · fail closed</span></summary><div className="network-grid"><Fact label="Gauge contract" value={compact(config.gaugeContract)} /><Fact label="Gauge code ID" value={String(config.gaugeCodeId)} /><Fact label="Voting module" value={compact(config.votingContract)} /><Fact label="Program Vault" value={compact(config.vaultContract)} /><Fact label="Registry adapter" value={compact(data.gauge.adapter)} /><Fact label="Observation height" value={data.observationHeight.toLocaleString()} /></div><p>Epoch options and tallies come only from the epoch-scoped snapshot. Current registry records are never used to rewrite historical facts.</p></details>
  </main>;
}

function EpochDetail({ epoch, data }: { epoch: Epoch; data: GaugeData }) {
  const isCurrent = data.current?.epochId === epoch.epochId, isPrevious = data.previous?.epochId === epoch.epochId;
  const options = isCurrent ? data.options : isPrevious ? data.previousOptions : [];
  return <article className="epoch-detail"><div className="epoch-heading"><div><span className="badge">{outcome(epoch)}</span><h3>Epoch {epoch.epochId}</h3></div><strong className="epoch-number">{String(epoch.epochId).padStart(2, "0")}</strong></div><div className="network-grid"><Fact label="Snapshot height" value={epoch.snapshotHeight.toLocaleString()} /><Fact label="Snapshot power" value={epoch.snapshotTotalPower} /><Fact label="Participating power" value={`${epoch.participatingPower} · ${percent(epoch.participatingPower, epoch.snapshotTotalPower)}`} /><Fact label="Allocated cast" value={epoch.totalCast} /><Fact label="Turnout floor" value={`${epoch.minTurnoutBps / 100}%`} /><Fact label="Fixed budget" value={juno(epoch.epochBudget)} /><Fact label="Opened" value={utc(epoch.opensAt)} /><Fact label="Closes" value={utc(epoch.closesAt)} /><Fact label="Voters" value={String(epoch.voterCount)} /><Fact label="Fixed options" value={String(epoch.optionCount)} /></div>
    {options.length > 0 ? <div className="allocation-list" aria-label="Fixed epoch allocation tallies">{options.map(({ option, power }) => <div className="allocation-row" key={option}><div><strong>{option}</strong>{option === "do-not-distribute" && <small>Retained in Program Vault</small>}</div><span>{power} power · {percent(power, epoch.totalCast)}</span></div>)}</div> : null}
    {options.length < epoch.optionCount && (epoch.cleanup.phase === "options" || epoch.cleanup.complete) ? <p className="notice" role="status">Bounded canonical cleanup removed {epoch.optionCount - options.length} fixed option/tally entr{epoch.optionCount - options.length === 1 ? "y" : "ies"}. Current registry options are intentionally not substituted.</p> : !isCurrent && !isPrevious ? <p className="notice" role="status">Only canonical current and previous epoch option snapshots are loaded. Historical summary facts remain fixed and authoritative.</p> : null}
    {epoch.outcome === "no_distribution_turnout" && <p className="notice">Turnout did not reach the fixed {epoch.minTurnoutBps / 100}% floor. The full budget remained in the Program Vault.</p>}
    {epoch.outcome === "no_eligible_options" && <p className="notice">No voted option survived execution-time eligibility and selection rules, or no positive ballot allocation existed. The full budget remained in the Program Vault.</p>}
    {epoch.outcome === "distributed" && <p className="notice">Canonical state records {epoch.messageCount} distribution message{epoch.messageCount === 1 ? "" : "s"}. The pinned schema does not retain exact emitted/retained amounts after execution; this interface does not infer them from current registry state.</p>}
  </article>;
}

function GaugeWorkbench({ data, source, config, transactionFlow, activeSender, setConnected }: { data: GaugeData; source: GaugeDataSource; config: AppConfig; transactionFlow?: GaugeTransactionFlow; activeSender: string | null; setConnected: (address: string) => void }) {
  const [weights, setWeights] = useState<Record<string, string>>(() => Object.fromEntries((data.ballot?.votes ?? []).map((vote) => [vote.option, vote.weight]))), [review, setReview] = useState<TransactionReview | null>(null), [outcomeState, setOutcome] = useState<TransactionOutcome | null>(null), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false), [locked, setLocked] = useState(false);
  const eligibility = gaugeEligibility({ data, fingerprint: "display" });
  const connect = async () => { if (!transactionFlow?.connect) return; setBusy(true); setError(null); try { setConnected((await transactionFlow.connect()).address); } catch (cause) { setError(cause instanceof Error ? cause.message : "Wallet connection failed."); } finally { setBusy(false); } };
  const prepare = async (action: GaugeAction) => { if (!transactionFlow || !activeSender || locked) return; setBusy(true); setError(null); setReview(null); setOutcome(null); try { const context = await source.loadActionContext(activeSender); const preferences: PreferenceInput[] = Object.entries(weights).filter(([, weight]) => weight.trim()).map(([option, weight]) => ({ option, weight: weight.trim() })); setReview(await transactionFlow.prepare(buildGaugeIntent(config, activeSender, context, action, preferences))); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gauge transaction preparation failed."); } finally { setBusy(false); } };
  const submit = async () => { if (!transactionFlow || !review) return; setBusy(true); setError(null); try { const result = await transactionFlow.submit(review); setOutcome(result); if (result.status === "pending" || result.status === "unknown") setLocked(true); setReview(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gauge transaction submission failed."); setReview(null); } finally { setBusy(false); } };
  return <section className="workbench gauge-workbench" aria-labelledby="gauge-actions"><div><p className="eyebrow">PUBLIC ACTIONS · TWO-STAGE REVIEW</p><h2 id="gauge-actions">Prepare exact transaction</h2><p>Preparation validates fixed-point weights, fixed epoch options, historical power, funding, stops, account, epoch identity, and canonical block time. The signing stage repeats the canonical checks.</p></div>
    {activeSender && <p className="notice" role="status">Connected account: {compact(activeSender)}{data.current && <> · snapshot power {data.votingPower?.power ?? "unavailable"}</>}</p>}
    {data.current?.outcome === "open" && <fieldset className="preference-editor" disabled={locked || busy || !eligibility.vote}><legend>Complete weighted ballot</legend>{data.options.map(({ option }) => <label key={option}><span>{option}{option === "do-not-distribute" && <small> retains value</small>}</span><input inputMode="decimal" aria-label={`Weight for ${option}`} placeholder="0.0" value={weights[option] ?? ""} onChange={(event) => { setWeights((current) => ({ ...current, [option]: event.target.value })); setReview(null); }} /></label>)}<p>Positive unique weights · maximum 18 decimal places · total ≤ 1 · every weighted power allocation must be nonzero.</p></fieldset>}
    {!transactionFlow ? <p className="notice" role="status">Supported Keplr or Leap transaction support is unavailable in this browser. Gauge history remains public.</p> : !activeSender ? <button className="button" disabled={busy || !transactionFlow.connect} onClick={connect}>{busy ? "Connecting wallet…" : "Connect wallet"}</button> : <div className="gauge-actions">{eligibility.open && <button className="button" disabled={busy || locked} onClick={() => prepare("open_epoch")}>Prepare open epoch</button>}{data.current?.outcome === "open" && <button className="button" disabled={busy || locked || !eligibility.vote} onClick={() => prepare("place_votes")}>{data.ballot ? "Prepare ballot revision" : "Prepare ballot"}</button>}{data.ballot && eligibility.vote && <button className="button secondary" disabled={busy || locked} onClick={() => prepare("remove_votes")}>Prepare ballot removal</button>}{eligibility.execute && <button className="button" disabled={busy || locked} onClick={() => prepare("execute")}>Prepare epoch execution</button>}{!eligibility.open && !eligibility.vote && !eligibility.execute && <p className="notice">No public gauge action is eligible at the observed canonical block time and state.</p>}</div>}
    {error && <p className="notice danger" role="alert">{error}</p>}
    {review && <div className="review" role="dialog" aria-modal="true" aria-labelledby="gauge-review-title"><h3 id="gauge-review-title">Exact transaction review</h3><p>No wallet signature has been requested. Verify the exact message and empty funds before continuing.</p><pre>{JSON.stringify({ sender: review.sender, chainId: review.chainId, contract: review.contract, msg: review.executeMessage, funds: review.funds, fee: review.fee, consequences: review.consequences, canonicalState: review.canonicalState }, null, 2)}</pre><div className="gauge-actions"><button className="button" disabled={busy} onClick={submit}>{busy ? "Rechecking canonical state…" : "Recheck state, then sign"}</button><button className="button secondary" disabled={busy} onClick={() => setReview(null)}>Cancel review</button></div></div>}
    {outcomeState && <p className="notice" role="status">{outcomeState.status === "confirmed" ? `Confirmed at height ${outcomeState.height}. Canonical state ${outcomeState.refreshStatus}.` : outcomeState.status === "failed" || outcomeState.status === "rejected" ? outcomeState.reason : "Submission is not canonically confirmed. Do not submit again until the account and transaction evidence are inspected."}</p>}
    {outcomeState && "explorerUrl" in outcomeState && outcomeState.explorerUrl && "txHash" in outcomeState && <p><a href={outcomeState.explorerUrl} target="_blank" rel="noopener noreferrer">View transaction evidence {outcomeState.txHash}</a></p>}
  </section>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="fact"><span>{label}</span><strong>{value}</strong></div>; }
function State({ title, detail, children }: { title: string; detail: string; children?: React.ReactNode }) { return <div className="state" role="status"><h2>{title}</h2><p>{detail}</p>{children}</div>; }
