import { useMemo, useState } from "react";
import type { AppConfig } from "./config";
import type { Project, ProjectDetail, RegistryDataSource } from "./registry";
import { useAsync } from "./useAsync";

const compact = (value: string) => value.length > 24 ? `${value.slice(0, 12)}…${value.slice(-6)}` : value;
const juno = (amount: string) => { const value = BigInt(amount), whole = value / 1_000_000n, fraction = (value % 1_000_000n).toString().padStart(6, "0").replace(/0+$/, ""); return `${whole.toLocaleString()}${fraction ? `.${fraction}` : ""} JUNO`; };
const utc = (nanos: string) => new Date(Number(BigInt(nanos) / 1_000_000n)).toISOString();
const statusLabel = (status: Project["status"]) => ({ pending: "Pending curator review", active: "Active", suspended: "Suspended by curator", rejected: "Rejected by curator", retired: "Retired" })[status];

export function Registry({ source, config }: { source: RegistryDataSource; config: AppConfig }) {
  const load = useMemo(() => () => source.loadRegistry(), [source]);
  const [state, retry] = useAsync(load, "registry");
  const [selected, setSelected] = useState<string | null>(null);
  if (state.kind === "loading") return <main><State title="Loading project registry…" detail="Verifying the registry deployment and querying canonical Juno state." /></main>;
  if (state.kind === "error") return <main><State title="Project registry unavailable" detail={state.message}><button className="button" onClick={retry}>Retry registry query</button></State></main>;
  const data = state.data;
  return <main>
    <section className="hero registry-hero" aria-labelledby="registry-title"><div><p className="eyebrow">HACK JUNO · PROJECT REGISTRY</p><h1 id="registry-title">Eligible projects</h1><p>Discover active gauge options and public applications from the verified registry. Project curation and governance states are visible; privileged controls are never exposed.</p></div><aside className="hero-summary" aria-label="Registry summary"><Fact label="Active" value={`${data.health.accounting.active_projects} / ${data.config.max_active_projects}`} /><Fact label="Applications" value={String(data.health.accounting.pending_applications)} /><Fact label="Accounting" value={data.health.fully_backed ? "Fully backed" : "Degraded"} /></aside></section>
    {(data.pause.admissions_stopped || data.pause.adapter_stopped) && <section className="notice" role="status"><strong>Registry stop is active.</strong> {data.pause.admissions_stopped && "New admissions are stopped. "}{data.pause.adapter_stopped && "Gauge distribution is stopped. "}{data.pause.reason}</section>}
    {!data.health.fully_backed && <section className="notice danger" role="alert"><strong>Bond accounting is not fully backed.</strong> Public write preparation is disabled.</section>}
    <section className="option-note"><strong>Gauge option: do-not-distribute</strong><p>This reserved choice intentionally retains that allocation in the program vault. It never pays a project and is not an active project ID.</p></section>
    <div className="registry-columns">
      <section aria-labelledby="active-projects"><div className="toolbar"><div><p className="eyebrow">GAUGE OPTIONS</p><h2 id="active-projects">Active projects</h2></div></div><ProjectList projects={data.projects} empty="No active projects" onSelect={setSelected} /></section>
      <section aria-labelledby="applications"><div className="toolbar"><div><p className="eyebrow">PUBLIC APPLICATIONS</p><h2 id="applications">Pending review</h2></div></div><ProjectList projects={data.applications} empty="No pending applications" onSelect={setSelected} /></section>
    </div>
    {selected && <ProjectPanel key={selected} id={selected} source={source} close={() => setSelected(null)} />}
    <ActionWorkbench data={data} config={config} />
    <section className="facts-panel" aria-labelledby="registry-economics"><h2 id="registry-economics">Live registration policy</h2><div className="network-grid"><Fact label="Exact registration bond" value={juno(data.config.registration_bond)} /><Fact label="Native denom" value={data.config.native_denom} /><Fact label="Metadata URI limit" value={`${data.config.max_metadata_uri_bytes} bytes`} /><Fact label="Payout delay" value={`${data.config.payout_address_delay_seconds}s`} /><Fact label="Bond liability" value={juno(data.health.accounting.bond_liability)} /><Fact label="Actual balance" value={juno(data.health.actual_native_balance)} /><Fact label="Curator (label only)" value={compact(data.config.curator)} /><Fact label="Governor (label only)" value={compact(data.config.governor)} /></div></section>
    <details className="network-details"><summary>Registry provenance <span>Weakly consistent direct-RPC observation</span></summary><div className="network-grid"><Fact label="Contract" value={compact(config.registryContract)} /><Fact label="Code ID" value={String(config.registryCodeId)} /><Fact label="Observation height" value={data.observationHeight.toLocaleString()} /><Fact label="Observed" value={data.refreshedAt.toISOString()} /></div><p>Pages are ordered by exclusive contract cursors and may change between queries. Every write must re-query canonical state and chain time before wallet review.</p></details>
  </main>;
}
function ProjectList({ projects, empty, onSelect }: { projects: Project[]; empty: string; onSelect: (id: string) => void }) {
  return <div className="project-list">{projects.length === 0 ? <State title={empty} detail="The verified contract returned an empty page." /> : projects.map((project) => <article className="project-card" key={project.id}><div><span className="badge">{statusLabel(project.status)}</span><h3>{project.id}</h3><p>Owner {compact(project.owner)}</p><small>Payout {compact(project.payout_address)}</small></div><button className="button secondary" onClick={() => onSelect(project.id)}>View canonical detail</button></article>)}</div>;
}
function ProjectPanel({ id, source, close }: { id: string; source: RegistryDataSource; close: () => void }) {
  const load = useMemo(() => () => source.loadProject(id), [source, id]); const [state, retry] = useAsync(load, `project ${id}`);
  return <section className="detail-panel" aria-labelledby="project-detail"><div className="toolbar"><h2 id="project-detail">Project detail · {id}</h2><button className="button secondary" onClick={close}>Close</button></div>{state.kind === "loading" ? <State title="Loading canonical detail…" detail="Querying project and complete histories." /> : state.kind === "error" ? <State title="Detail unavailable" detail={state.message}><button className="button" onClick={retry}>Retry detail</button></State> : <Detail detail={state.data} />}</section>;
}
function Detail({ detail: { project: p, statusHistory, addressHistory } }: { detail: ProjectDetail }) {
  return <div className="detail-grid"><div><h3>Canonical record</h3><dl><dt>Status</dt><dd>{statusLabel(p.status)}</dd><dt>Owner</dt><dd className="break">{p.owner}</dd><dt>Payout</dt><dd className="break">{p.payout_address}</dd><dt>Metadata URI</dt><dd className="break"><a href={p.metadata_uri} target="_blank" rel="noreferrer">{p.metadata_uri}</a></dd><dt>Metadata digest</dt><dd className="break">{p.metadata_digest}</dd><dt>Admission</dt><dd>{p.provenance.kind === "bonded_registration" ? "Bonded public registration" : `Graduated bounty #${p.provenance.source_bounty_id}`}</dd>{p.bond && <><dt>Registration bond</dt><dd>{juno(p.bond.amount)} · {p.bond.state}</dd></>}{p.latest_review && <><dt>Latest curator review</dt><dd>{p.latest_review.code.replaceAll("_", " ")} · {p.latest_review.note}</dd></>}</dl>{p.pending_payout_address && <div className="notice"><strong>Pending payout address</strong><p className="break">{p.pending_payout_address.address}</p><p>Acceptable by the proposed address at or after <time dateTime={utc(p.pending_payout_address.executable_at)}>{utc(p.pending_payout_address.executable_at)}</time>, subject to canonical chain time.</p></div>}</div><div><History title="Status history" entries={statusHistory.map((h) => ({ key: h.sequence, title: `${h.from ?? "new"} → ${h.to}`, detail: `${h.action} · ${utc(h.at)} · ${compact(h.actor)}` }))} /><History title="Payout address history" entries={addressHistory.map((h) => ({ key: h.sequence, title: h.action, detail: `${h.proposed_address ? compact(h.proposed_address) : "No proposed address"} · ${utc(h.at)}` }))} /></div></div>;
}
function History({ title, entries }: { title: string; entries: { key: number; title: string; detail: string }[] }) { return <section className="history"><h3>{title}</h3>{entries.length ? <ol>{entries.map((e) => <li key={e.key}><strong>{e.title}</strong><small>{e.detail}</small></li>)}</ol> : <p>No history entries.</p>}</section>; }
function ActionWorkbench({ data, config }: { data: Awaited<ReturnType<RegistryDataSource["loadRegistry"]>>; config: AppConfig }) {
  const [action, setAction] = useState("register_project"), [projectId, setProjectId] = useState(""), [metadataUri, setMetadataUri] = useState(""), [digest, setDigest] = useState(""), [address, setAddress] = useState(""), [note, setNote] = useState("");
  const project = [...data.projects, ...data.applications].find((p) => p.id === projectId), body = action === "register_project" ? { project_id: projectId, metadata_uri: metadataUri, metadata_digest: digest, payout_address: address } : action === "update_pending_metadata" ? { project_id: projectId, metadata_uri: metadataUri, metadata_digest: digest } : action === "propose_payout_address" ? { project_id: projectId, address } : action === "retire" ? { project_id: projectId, reason: { code: "voluntary_retirement", note } } : { project_id: projectId };
  const funds = action === "register_project" ? [{ denom: data.config.native_denom, amount: data.config.registration_bond }] : [];
  const unavailable = data.pause.admissions_stopped || !data.health.fully_backed || (action === "update_pending_metadata" && project?.status !== "pending") || (action === "claim_registration_bond" && project?.bond?.state !== "claimable") || (action === "accept_payout_address" && !project?.pending_payout_address);
  return <section className="workbench" aria-labelledby="public-actions"><div><p className="eyebrow">OWNER / PUBLIC LIFECYCLE</p><h2 id="public-actions">Prepare exact transaction</h2><p>This bounded workbench creates a transparent unsigned message only. It never signs or broadcasts. A wallet integration must re-check ownership, live stop/capacity, bond state, and chain time through the #32 review lifecycle.</p></div><div className="form-grid"><label>Public action<select value={action} onChange={(e) => setAction(e.target.value)}><option value="register_project">Register project</option><option value="update_pending_metadata">Update pending metadata</option><option value="propose_payout_address">Propose payout address</option><option value="cancel_payout_address_change">Cancel payout change</option><option value="accept_payout_address">Accept delayed payout</option><option value="retire">Voluntary retirement</option><option value="claim_registration_bond">Claim registration bond</option></select></label><label>Project ID<input value={projectId} onChange={(e) => setProjectId(e.target.value)} /></label>{["register_project", "update_pending_metadata"].includes(action) && <><label>Metadata URI<input value={metadataUri} maxLength={data.config.max_metadata_uri_bytes} onChange={(e) => setMetadataUri(e.target.value)} /></label><label>Metadata digest<input value={digest} onChange={(e) => setDigest(e.target.value)} /></label></>}{["register_project", "propose_payout_address"].includes(action) && <label>Payout address<input value={address} onChange={(e) => setAddress(e.target.value)} /></label>}{action === "retire" && <label>Retirement note<input value={note} maxLength={data.config.max_reason_bytes} onChange={(e) => setNote(e.target.value)} /></label>}</div>{unavailable && <p className="notice" role="status">This action is not currently available from observed state. Refresh and resolve the displayed stop, health, status, delay, or claimability boundary.</p>}<div className="review-card"><h3>Unsigned exact review</h3><Fact label="Chain" value={config.chainId} /><Fact label="Contract" value={config.registryContract} /><Fact label="Funds" value={funds.length ? `${funds[0].amount} ${funds[0].denom}` : "None"} /><pre>{JSON.stringify({ [action]: body }, null, 2)}</pre><p><strong>No signature requested. Nothing broadcast.</strong></p></div></section>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className="fact"><span>{label}</span><strong>{value}</strong></div>; }
function State({ title, detail, children }: { title: string; detail: string; children?: React.ReactNode }) { return <div className="state" role="status"><h2>{title}</h2><p>{detail}</p>{children}</div>; }
