import { useEffect,useState } from 'react';
import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,expect,it,vi } from 'vitest';
import { TimeoutError } from '@cosmjs/stargate';
import { App } from './App';
import { Ledger } from './Ledger';
import { RequestActions, SubmitAction, WalletButton } from './WalletActions';
import { buildRefundReview,buildSubmitReview,PublicTransactions,WalletConnection,type SigningClient,type TransactionReceipt } from './wallet';
import { config,ledger,request } from './test/fixtures';

const confirmed:TransactionReceipt={status:'confirmed',hash:'ABC123',explorerUrl:`${config.explorer}/tx/ABC123`,requestId:7};

describe('explicit voting gate and refund eligibility UI',()=>{
  it('never enables vote execution and exposes refund only to an eligible author',()=>{const transactions={} as PublicTransactions;const {rerender}=render(<RequestActions request={request} account={request.author} transactions={transactions} onSuccess={vi.fn()}/>);expect(screen.getByText(/Voting execution disabled by safety gate/)).toBeInTheDocument();expect(screen.getByRole('button',{name:/SUPPORT unavailable/})).toBeDisabled();expect(screen.getByRole('button',{name:/OPPOSE unavailable/})).toBeDisabled();expect(screen.getByRole('button',{name:'Review refund'})).toBeEnabled();rerender(<RequestActions request={{...request,bond:{...request.bond,state:'locked'}}} account={request.author} transactions={transactions} onSuccess={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Review refund'})).not.toBeInTheDocument();expect(screen.getByText(/not currently refundable/)).toBeInTheDocument()});
});

describe('transaction status UI',()=>{
  it('shows submit preparation errors inline without window.alert',async()=>{const user=userEvent.setup();const alert=vi.spyOn(window,'alert').mockImplementation(()=>undefined);const transactions={reviewSubmit:vi.fn().mockRejectedValue(new Error('Title is required.'))} as unknown as PublicTransactions;render(<SubmitAction account={request.author} transactions={transactions} live={ledger.config}/>);await user.click(screen.getByRole('button',{name:'New request'}));await user.click(screen.getByRole('button',{name:'Review exact transaction'}));expect(await screen.findByRole('alert')).toHaveTextContent('Title is required.');expect(alert).not.toHaveBeenCalled();alert.mockRestore()});
  it('renders a real CosmJS timeout as non-retryable, preserves its hash, and invokes confirm once',async()=>{const user=userEvent.setup();const execute=vi.fn().mockRejectedValue(new TimeoutError('submitted but not found','PENDING7'));const client={execute,disconnect:vi.fn()} as unknown as SigningClient;const signer={getAccounts:vi.fn().mockResolvedValue([{address:request.author}])};const extension={enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const wallet=new WalletConnection(config,{keplr:extension,addEventListener:vi.fn(),removeEventListener:vi.fn()} as unknown as Window,vi.fn().mockResolvedValue(client));await wallet.connect();const transactions=new PublicTransactions(config,{config:vi.fn().mockResolvedValue(ledger.config),request:vi.fn().mockResolvedValue(request)},wallet);const confirm=vi.spyOn(transactions,'confirm');render(<RequestActions request={request} account={request.author} transactions={transactions}/>);await user.click(screen.getByRole('button',{name:'Review refund'}));await user.click(await screen.findByRole('button',{name:'Confirm in wallet'}));expect(await screen.findByText(/Broadcast submitted — confirmation pending/)).toBeInTheDocument();expect(screen.getByRole('link',{name:/PENDING7/})).toHaveAttribute('href',`${config.explorer}/tx/PENDING7`);expect(screen.queryByRole('button',{name:'Confirm in wallet'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Back'})).not.toBeInTheDocument();expect(confirm).toHaveBeenCalledTimes(1);expect(execute).toHaveBeenCalledTimes(1)});
  it('renders a hashless unknown broadcast as non-retryable without inventing an explorer link',async()=>{const user=userEvent.setup();const review=buildRefundReview(config,request.author,request);const unknown:TransactionReceipt={status:'broadcast_unknown',hash:null,explorerUrl:null,requestId:null,detail:'The transaction may have been submitted. Verify on chain; do not broadcast again.'};const transactions={reviewRefund:vi.fn().mockResolvedValue(review),confirm:vi.fn().mockResolvedValue(unknown)} as unknown as PublicTransactions;render(<RequestActions request={request} account={request.author} transactions={transactions}/>);await user.click(screen.getByRole('button',{name:'Review refund'}));await user.click(await screen.findByRole('button',{name:'Confirm in wallet'}));expect(await screen.findByText(/Broadcast outcome unknown — verification required/)).toBeInTheDocument();expect(screen.getByText(/broadcast may have occurred/i)).toBeInTheDocument();expect(screen.queryByRole('link')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Confirm in wallet'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Back'})).not.toBeInTheDocument();expect(transactions.confirm).toHaveBeenCalledTimes(1)});
  it('refreshes canonical ledger data while the confirmed receipt remains visible',async()=>{const user=userEvent.setup();const input={title:'Ship safely',summary:'A clear summary',acceptance_criteria:'All tests pass',category:'infrastructure',detail_uri:'',detail_digest:''};const review=buildSubmitReview(config,request.author,ledger.config,input);const transactions={reviewSubmit:vi.fn().mockResolvedValue(review),confirm:vi.fn().mockResolvedValue(confirmed)} as unknown as PublicTransactions;const source={loadLedger:vi.fn().mockResolvedValue(ledger),loadDetail:vi.fn()};function Harness(){const [refresh,setRefresh]=useState(0);return <Ledger source={source} config={config} account={request.author} transactions={transactions} refreshToken={refresh} onSuccess={()=>setRefresh(value=>value+1)} onOpen={vi.fn()}/>}render(<Harness/>);await screen.findByRole('heading',{name:'Signal ledger'});await user.click(screen.getByRole('button',{name:'New request'}));for(const [name,value] of [['Title',input.title],['Summary',input.summary],['Acceptance criteria',input.acceptance_criteria],['Category',input.category]])await user.type(screen.getByLabelText(new RegExp(`^${name}`)),value);await user.click(screen.getByRole('button',{name:'Review exact transaction'}));await user.click(await screen.findByRole('button',{name:'Confirm in wallet'}));expect(await screen.findByRole('link',{name:/ABC123/})).toHaveAttribute('href',confirmed.explorerUrl);await waitFor(()=>expect(source.loadLedger).toHaveBeenCalledTimes(2));expect(screen.getByRole('link',{name:/ABC123/})).toBeInTheDocument()});
});

describe('App wallet lifecycle',()=>{
  it('unsubscribes and disconnects its wallet on cleanup',async()=>{const unsubscribe=vi.fn();const onChange=vi.spyOn(WalletConnection.prototype,'onChange').mockReturnValue(unsubscribe);const disconnect=vi.spyOn(WalletConnection.prototype,'disconnect').mockImplementation(()=>undefined);const source={loadLedger:vi.fn().mockResolvedValue(ledger),loadDetail:vi.fn()};const view=render(<App source={source} config={config}/>);await screen.findByRole('heading',{name:'Signal ledger'});view.unmount();expect(onChange).toHaveBeenCalled();expect(unsubscribe).toHaveBeenCalledTimes(1);expect(disconnect).toHaveBeenCalledTimes(1);onChange.mockRestore();disconnect.mockRestore()});
  it('invalidates an in-flight connect on component unmount and closes its late client',async()=>{let resolveClient!:(client:SigningClient)=>void;const lateClient={disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient;const signing=new Promise<SigningClient>(resolve=>{resolveClient=resolve});const addEventListener=vi.fn();const signer={getAccounts:vi.fn().mockResolvedValue([{address:request.author}])};const extension={enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const wallet=new WalletConnection(config,{keplr:extension,addEventListener,removeEventListener:vi.fn()} as unknown as Window,()=>signing);function Harness(){const [account,setAccount]=useState<string|null>(null);useEffect(()=>()=>wallet.disconnect(),[]);return <WalletButton wallet={wallet} account={account} onAccount={setAccount}/>}const user=userEvent.setup();const view=render(<Harness/>);await user.click(screen.getByRole('button',{name:'Connect Keplr / Leap'}));await waitFor(()=>expect(signer.getAccounts).toHaveBeenCalled());view.unmount();resolveClient(lateClient);await waitFor(()=>expect(lateClient.disconnect).toHaveBeenCalledTimes(1));expect(wallet.account).toBeNull();expect(addEventListener).not.toHaveBeenCalled()});
});
