import { describe,expect,it,vi } from 'vitest';
import { TimeoutError } from '@cosmjs/stargate';
import { buildRefundReview,buildSubmitReview,chainInfo,mapTransactionError,PublicTransactions,refundEligible,WalletConnection,type ExecuteResult,type LatestState,type SigningClient,type SubmitInput,type WalletExtension } from './wallet';
import { config,ledger,request } from './test/fixtures';

const sender=request.author;
const input:SubmitInput={title:'Ship safely',summary:'A clear summary',acceptance_criteria:'All tests pass',category:'infrastructure',detail_uri:'',detail_digest:''};
function deferred<T>(){let resolve!:(value:T)=>void;let reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}}
describe('safe message construction',()=>{
  it('uses live config for exact message, denom, bond, and UTF-8 limits',()=>{const review=buildSubmitReview(config,sender,ledger.config,input);expect(review).toMatchObject({chainId:'uni-7',sender,contract:config.contract,message:{submit_request:{...input,detail_uri:null,detail_digest:null}},funds:[{denom:'ujunox',amount:'1000000'}]});expect(()=>buildSubmitReview(config,sender,{...ledger.config,request_limits:{...ledger.config.request_limits,max_title_bytes:4}},{...input,title:'ééé'})).toThrow(/4-byte/)});
  it('requires paired valid detail metadata and rejects paused state',()=>{expect(()=>buildSubmitReview(config,sender,ledger.config,{...input,detail_uri:'https://x',detail_digest:''})).toThrow(/together/);expect(()=>buildSubmitReview(config,sender,{...ledger.config,submissions_paused:true},input)).toThrow(/paused/)});
  it('builds only an author refund with no funds',()=>{expect(refundEligible(request,sender)).toBe(true);expect(buildRefundReview(config,sender,request).message).toEqual({withdraw_refund:{request_id:7}});expect(buildRefundReview(config,sender,request).funds).toEqual([]);expect(()=>buildRefundReview(config,'juno1other',{...request,bond:{...request.bond,state:'locked'}})).toThrow(/Refund unavailable/)});
  it('pins exact current uni-7 registry REST endpoint and denom',()=>expect(chainInfo(config)).toMatchObject({chainId:'uni-7',rest:'https://juno-testnet-api.polkachu.com',currencies:[{coinMinimalDenom:'ujunox'}]}));
});

describe('wallet connection',()=>{
  it('fails closed for missing, rejected, locked, and wrong-chain wallets',async()=>{await expect(new WalletConnection(config,{} as Window).connect()).rejects.toThrow(/No compatible wallet/);expect(mapTransactionError(new Error('Request rejected'))).toHaveProperty('message','Wallet request rejected. No transaction was broadcast.');expect(mapTransactionError(new Error('wallet locked')).message).toMatch(/locked/);const extension={experimentalSuggestChain:vi.fn(),enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('juno-1'),getOfflineSigner:vi.fn()} as unknown as WalletExtension;await expect(new WalletConnection(config,{keplr:extension,addEventListener:vi.fn(),removeEventListener:vi.fn()} as unknown as Window).connect()).rejects.toThrow(/Wrong chain/)});
  it('disconnects on wallet change and removes every installed browser listener',async()=>{const callbacks:Record<string,EventListener>={};const removeEventListener=vi.fn();const signer={getAccounts:vi.fn().mockResolvedValue([{address:sender}])};const client={disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient;const extension={experimentalSuggestChain:vi.fn(),enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const browser={keplr:extension,addEventListener:vi.fn((name:string,callback:EventListener)=>{callbacks[name]=callback}),removeEventListener} as unknown as Window;const wallet=new WalletConnection(config,browser,vi.fn().mockResolvedValue(client));await wallet.connect();callbacks.keplr_keystorechange(new Event('x'));expect(wallet.account).toBeNull();expect(client.disconnect).toHaveBeenCalled();expect(removeEventListener).toHaveBeenCalledTimes(3)});
  it('does not accumulate stale once-listeners across manual disconnect and reconnect',async()=>{const active=new Map<string,Set<EventListener>>();const addEventListener=vi.fn((name:string,callback:EventListener)=>{const set=active.get(name)??new Set();set.add(callback);active.set(name,set)});const removeEventListener=vi.fn((name:string,callback:EventListener)=>active.get(name)?.delete(callback));const signer={getAccounts:vi.fn().mockResolvedValue([{address:sender}])};const extension={enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const browser={keplr:extension,addEventListener,removeEventListener} as unknown as Window;const makeClient=()=>({disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient);const wallet=new WalletConnection(config,browser,vi.fn().mockImplementation(async()=>makeClient()));await wallet.connect();wallet.disconnect();await wallet.connect();expect([...active.values()].map(set=>set.size)).toEqual([1,1,1]);expect(removeEventListener).toHaveBeenCalledTimes(3)});
  it('closes a client that finishes after manual disconnect and never installs stale state or listeners',async()=>{const gate=deferred<SigningClient>();const stale={disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient;const addEventListener=vi.fn();const signer={getAccounts:vi.fn().mockResolvedValue([{address:sender}])};const extension={enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const wallet=new WalletConnection(config,{keplr:extension,addEventListener,removeEventListener:vi.fn()} as unknown as Window,()=>gate.promise);const connecting=wallet.connect();await vi.waitFor(()=>expect(signer.getAccounts).toHaveBeenCalled());wallet.disconnect();gate.resolve(stale);await expect(connecting).rejects.toThrow(/superseded/);expect(stale.disconnect).toHaveBeenCalledTimes(1);expect(wallet.account).toBeNull();expect(addEventListener).not.toHaveBeenCalled()});
  it('lets only the newest overlapping connect win when clients finish out of order',async()=>{const firstGate=deferred<SigningClient>(),secondGate=deferred<SigningClient>();const stale={disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient;const newest={disconnect:vi.fn(),execute:vi.fn()} as unknown as SigningClient;const addEventListener=vi.fn();const signer={getAccounts:vi.fn().mockResolvedValue([{address:sender}])};const extension={enable:vi.fn(),getChainId:vi.fn().mockResolvedValue('uni-7'),getOfflineSigner:()=>signer};const connector=vi.fn().mockImplementationOnce(()=>firstGate.promise).mockImplementationOnce(()=>secondGate.promise);const wallet=new WalletConnection(config,{keplr:extension,addEventListener,removeEventListener:vi.fn()} as unknown as Window,connector);const first=wallet.connect();const firstOutcome=first.catch(error=>error);await vi.waitFor(()=>expect(connector).toHaveBeenCalledTimes(1));const second=wallet.connect();await vi.waitFor(()=>expect(connector).toHaveBeenCalledTimes(2));secondGate.resolve(newest);await expect(second).resolves.toBe(sender);firstGate.resolve(stale);expect(await firstOutcome).toEqual(expect.objectContaining({message:expect.stringMatching(/superseded/)}));expect(wallet.account).toBe(sender);expect(wallet.signingClient()).toBe(newest);expect(addEventListener).toHaveBeenCalledTimes(3);expect(stale.disconnect).toHaveBeenCalledTimes(1);expect(newest.disconnect).not.toHaveBeenCalled()});
});

describe('live re-query, identity revalidation, execution and canonical confirmation',()=>{
  function harness(result:ExecuteResult,canonical=request,confirmationTimeoutMs=8_000){
    const execute=vi.fn().mockResolvedValue(result);
    const client={execute,disconnect:vi.fn()} as unknown as SigningClient;
    const getChainId=vi.fn().mockResolvedValue('uni-7');
    const getAccounts=vi.fn().mockResolvedValue([{address:sender}]);
    const extension={enable:vi.fn(),getChainId,getOfflineSigner:()=>({getAccounts})};
    const browser={keplr:extension,addEventListener:vi.fn(),removeEventListener:vi.fn()} as unknown as Window;
    const wallet=new WalletConnection(config,browser,vi.fn().mockResolvedValue(client));
    const latest:LatestState={config:vi.fn().mockResolvedValue(ledger.config),request:vi.fn().mockResolvedValue(canonical)};
    return {wallet,latest,execute,getChainId,getAccounts,tx:new PublicTransactions(config,latest,wallet,confirmationTimeoutMs)};
  }
  it('re-queries, immediately revalidates chain/account, confirms canonical data, and returns link',async()=>{const h=harness({code:0,transactionHash:'ABC',events:[{type:'wasm',attributes:[{key:'request_id',value:'7'}]}]},{...request,author:sender,title:input.title,summary:input.summary,acceptance_criteria:input.acceptance_criteria,category:input.category,detail_uri:null,detail_digest:null});await h.wallet.connect();const review=await h.tx.reviewSubmit(input);const receipt=await h.tx.confirm(review);expect(h.latest.config).toHaveBeenCalledTimes(2);expect(h.getChainId).toHaveBeenCalledTimes(2);expect(h.getAccounts).toHaveBeenCalledTimes(2);expect(h.execute).toHaveBeenCalledWith(sender,config.contract,review.message,'auto','Juno Voice',[{denom:'ujunox',amount:'1000000'}]);expect(receipt).toEqual({status:'confirmed',hash:'ABC',explorerUrl:`${config.explorer}/tx/ABC`,requestId:7})});
  it('fails closed on delayed chain and account races without execute',async()=>{const chain=harness({code:0,transactionHash:'never'});await chain.wallet.connect();const chainReview=await chain.tx.reviewSubmit(input);chain.getChainId.mockResolvedValueOnce('juno-1');await expect(chain.tx.confirm(chainReview)).rejects.toThrow(/chain changed/i);expect(chain.execute).not.toHaveBeenCalled();const account=harness({code:0,transactionHash:'never'});await account.wallet.connect();const accountReview=await account.tx.reviewSubmit(input);account.getAccounts.mockResolvedValueOnce([{address:'juno1changed'}]);await expect(account.tx.confirm(accountReview)).rejects.toThrow(/account changed/i);expect(account.execute).not.toHaveBeenCalled()});
  it('blocks stale canonical state before wallet invocation',async()=>{const h=harness({code:0,transactionHash:'never'});await h.wallet.connect();const review=await h.tx.reviewSubmit(input);vi.mocked(h.latest.config).mockResolvedValueOnce({...ledger.config,submission_bond:'2000000'});await expect(h.tx.confirm(review)).rejects.toThrow(/state changed/);expect(h.execute).not.toHaveBeenCalled()});
  it('models accepted broadcasts with delayed/failed canonical queries as non-retryable pending receipts',async()=>{const h=harness({code:0,transactionHash:'PENDING',events:[{type:'wasm',attributes:[{key:'request_id',value:'7'}]}]});await h.wallet.connect();const review=await h.tx.reviewSubmit(input);vi.mocked(h.latest.request).mockRejectedValueOnce(new Error('RPC timeout'));await expect(h.tx.confirm(review)).resolves.toMatchObject({status:'confirmation_pending',hash:'PENDING',explorerUrl:`${config.explorer}/tx/PENDING`,requestId:7,detail:expect.stringMatching(/Do not broadcast again/i)});expect(h.execute).toHaveBeenCalledTimes(1)});
  it('turns a real CosmJS TimeoutError into a hash-preserving non-retryable pending receipt',async()=>{const h=harness({code:0,transactionHash:'unused'});h.execute.mockRejectedValueOnce(new TimeoutError('submitted but not found','TIMEOUT-HASH'));await h.wallet.connect();const receipt=await h.tx.confirm(await h.tx.reviewSubmit(input));expect(receipt).toMatchObject({status:'confirmation_pending',hash:'TIMEOUT-HASH',explorerUrl:`${config.explorer}/tx/TIMEOUT-HASH`,requestId:null,detail:expect.stringMatching(/do not broadcast/i)});expect(h.execute).toHaveBeenCalledTimes(1)});
  it('models a hashless network failure during broadcast as unknown and non-retryable',async()=>{const h=harness({code:0,transactionHash:'unused'});h.execute.mockRejectedValueOnce(new TypeError('Failed to fetch RPC response: socket closed'));await h.wallet.connect();const receipt=await h.tx.confirm(await h.tx.reviewSubmit(input));expect(receipt).toEqual({status:'broadcast_unknown',hash:null,explorerUrl:null,requestId:null,detail:expect.stringMatching(/may have been submitted.*do not broadcast/is)});expect(h.execute).toHaveBeenCalledTimes(1)});
  it('does not mistake block-polling failures for a definitely pre-broadcast wallet lock',async()=>{const h=harness({code:0,transactionHash:'unused'});h.execute.mockRejectedValueOnce(new Error('RPC block polling network failure'));await h.wallet.connect();await expect(h.tx.confirm(await h.tx.reviewSubmit(input))).resolves.toMatchObject({status:'broadcast_unknown'});expect(h.execute).toHaveBeenCalledTimes(1)});
  it('keeps exact wallet rejection retryable but treats generic canceled broadcast responses as unknown',async()=>{const rejected=harness({code:0,transactionHash:'unused'});rejected.execute.mockRejectedValueOnce(new Error('Request rejected'));await rejected.wallet.connect();await expect(rejected.tx.confirm(await rejected.tx.reviewSubmit(input))).rejects.toThrow(/Wallet request rejected/);const ambiguous=harness({code:0,transactionHash:'unused'});ambiguous.execute.mockRejectedValueOnce(new Error('context canceled while waiting for broadcast response'));await ambiguous.wallet.connect();await expect(ambiguous.tx.confirm(await ambiguous.tx.reviewSubmit(input))).resolves.toMatchObject({status:'broadcast_unknown'});expect(ambiguous.execute).toHaveBeenCalledTimes(1)});
  it('bounds a delayed canonical query and retains the accepted hash',async()=>{const h=harness({code:0,transactionHash:'SLOW',events:[{type:'wasm',attributes:[{key:'request_id',value:'7'}]}]},request,1);await h.wallet.connect();const review=await h.tx.reviewSubmit(input);vi.mocked(h.latest.request).mockImplementationOnce(()=>new Promise(()=>undefined));await expect(h.tx.confirm(review)).resolves.toMatchObject({status:'confirmation_pending',hash:'SLOW',detail:expect.stringMatching(/timed out/)});expect(h.execute).toHaveBeenCalledTimes(1)});
  it('preserves the hash when accepted submit events do not yet expose a request ID',async()=>{const h=harness({code:0,transactionHash:'NOEVENT'});await h.wallet.connect();const receipt=await h.tx.confirm(await h.tx.reviewSubmit(input));expect(receipt).toMatchObject({status:'confirmation_pending',hash:'NOEVENT',requestId:null});expect(h.latest.request).not.toHaveBeenCalled()});
  it('requires code zero and confirms a claimed refund',async()=>{const failed=harness({code:5,transactionHash:'BAD',rawLog:'contract error'});await failed.wallet.connect();await expect(failed.tx.confirm(await failed.tx.reviewRefund(7))).rejects.toThrow(/code 5/);const good=harness({code:0,transactionHash:'REFUND'},{...request,bond:{...request.bond,state:'claimed'}});vi.mocked(good.latest.request).mockResolvedValueOnce(request).mockResolvedValueOnce(request).mockResolvedValueOnce({...request,bond:{...request.bond,state:'claimed'}});await good.wallet.connect();expect(await good.tx.confirm(await good.tx.reviewRefund(7))).toMatchObject({status:'confirmed',hash:'REFUND',requestId:7})});
});
