import { useState } from 'react';
import type { ContractConfig,Request } from './types';
import type { PublicTransactions,SubmitInput,TransactionReceipt,TransactionReview,WalletConnection } from './wallet';

export function WalletButton({wallet,account,onAccount}:{wallet:WalletConnection;account:string|null;onAccount:(value:string|null)=>void}){
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const connect=async()=>{setBusy(true);setError('');try{onAccount(await wallet.connect())}catch(value){setError(value instanceof Error?value.message:'Wallet unavailable.')}finally{setBusy(false)}};
  return <div className="wallet-connect">{account?<><span title={account}>{account.slice(0,10)}…{account.slice(-6)}</span><button className="button" onClick={()=>{wallet.disconnect();onAccount(null)}}>Disconnect</button></>:<button className="button primary" disabled={busy} onClick={connect}>{busy?'Connecting…':'Connect Keplr / Leap'}</button>}{error&&<span className="action-error" role="alert">{error}</span>}</div>;
}

const empty:SubmitInput={title:'',summary:'',acceptance_criteria:'',category:'',detail_uri:'',detail_digest:''};
type ReceiptHandler=(receipt:TransactionReceipt)=>void;
export function SubmitAction({account,transactions,live,onSuccess=()=>undefined}:{account:string|null;transactions:PublicTransactions;live:ContractConfig;onSuccess?:ReceiptHandler}){
  const [open,setOpen]=useState(false),[input,setInput]=useState(empty),[review,setReview]=useState<TransactionReview|null>(null),[error,setError]=useState('');
  return <section className="public-action"><h2>Submit a public request</h2>{!account?<p>Connect a wallet to prepare a submission. Reading remains available without a wallet.</p>:!open?<button className="button primary" disabled={live.submissions_paused} onClick={()=>setOpen(true)}>{live.submissions_paused?'Submissions paused':'New request'}</button>:review?<Review review={review} transactions={transactions} onCancel={()=>setReview(null)} onSuccess={receipt=>{setInput(empty);onSuccess(receipt)}}/>:<form onSubmit={async event=>{event.preventDefault();setError('');try{setReview(await transactions.reviewSubmit(input))}catch(value){setError(value instanceof Error?value.message:'Unable to prepare transaction.')}}}><Field label={`Title · max ${live.request_limits.max_title_bytes} bytes`} value={input.title} onChange={title=>setInput({...input,title})}/><Field label={`Summary · max ${live.request_limits.max_summary_bytes} bytes`} value={input.summary} area onChange={summary=>setInput({...input,summary})}/><Field label={`Acceptance criteria · max ${live.request_limits.max_acceptance_criteria_bytes} bytes`} value={input.acceptance_criteria} area onChange={acceptance_criteria=>setInput({...input,acceptance_criteria})}/><Field label={`Category · max ${live.request_limits.max_category_bytes} bytes`} value={input.category} onChange={category=>setInput({...input,category})}/><Field label="Detail URI (optional; requires digest)" value={input.detail_uri} onChange={detail_uri=>setInput({...input,detail_uri})}/><Field label="sha256 digest (optional; requires URI)" value={input.detail_digest} onChange={detail_digest=>setInput({...input,detail_digest})}/><p>Live bond: <strong>{live.submission_bond} {live.native_denom}</strong></p>{error&&<p className="action-error" role="alert">{error}</p>}<button className="button primary">Review exact transaction</button> <button type="button" className="button" onClick={()=>{setOpen(false);setError('')}}>Cancel</button></form>}</section>;
}
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(value:string)=>void;area?:boolean}){return <label className="write-field">{label}{area?<textarea value={value} onChange={event=>onChange(event.target.value)}/>:<input value={value} onChange={event=>onChange(event.target.value)}/>}</label>}

export function RequestActions({request,account,transactions,onSuccess=()=>undefined}:{request:Request;account:string|null;transactions:PublicTransactions;onSuccess?:ReceiptHandler}){
  const [review,setReview]=useState<TransactionReview|null>(null),[error,setError]=useState('');
  const eligible=Boolean(account)&&request.author===account&&request.bond.state==='refundable'&&/^\d+$/.test(request.bond.amount)&&BigInt(request.bond.amount)>0n;
  return <section className="public-action"><h2>Public wallet actions</h2><div className="vote-gate" role="status"><strong>Voting execution disabled by safety gate</strong><p>SUPPORT and OPPOSE are immutable, but direct typed historical voter power at this request’s snapshot cannot currently be verified. Current wallet balance is never substituted.</p><button className="button" disabled>SUPPORT unavailable</button> <button className="button" disabled>OPPOSE unavailable</button></div><h3>Bond refund</h3>{!account?<p>Connect the request author’s wallet to check refund eligibility.</p>:eligible?review?<Review review={review} transactions={transactions} onCancel={()=>setReview(null)} onSuccess={onSuccess}/>:<button className="button primary" onClick={async()=>{setError('');try{setReview(await transactions.reviewRefund(request.id))}catch(value){setError(value instanceof Error?value.message:'Refund unavailable.')}}}>Review refund</button>:<p>Unavailable: the connected account is not the author, or this bond is not currently refundable.</p>}{error&&<p className="action-error" role="alert">{error}</p>}</section>;
}

export function TransactionReceiptView({receipt}:{receipt:TransactionReceipt}){
  const pending=receipt.status==='confirmation_pending';
  return <div className={`tx-success ${pending?'tx-pending':''}`} role="status"><strong>{pending?'Broadcast accepted — confirmation pending':'Canonical transaction confirmed'}</strong>{pending&&<p>This transaction was accepted by the network. Confirm is disabled to prevent a duplicate broadcast.</p>}{receipt.detail&&<p>{receipt.detail}</p>}<a href={receipt.explorerUrl} target="_blank" rel="noopener noreferrer">View {receipt.hash} on Mintscan</a></div>;
}
function Review({review,transactions,onCancel,onSuccess}:{review:TransactionReview;transactions:PublicTransactions;onCancel:()=>void;onSuccess:ReceiptHandler}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<TransactionReceipt|null>(null);
  if(receipt)return <TransactionReceiptView receipt={receipt}/>;
  return <div className="review"><h3>Exact pre-sign review</h3><dl><dt>Chain ID</dt><dd>{review.chainId}</dd><dt>Sender</dt><dd>{review.sender}</dd><dt>Contract</dt><dd>{review.contract}</dd><dt>Execute message</dt><dd><pre>{JSON.stringify(review.message,null,2)}</pre></dd><dt>Attached funds</dt><dd><pre>{JSON.stringify(review.funds,null,2)}</pre></dd></dl><ul>{review.implications.map(item=><li key={item}>{item}</li>)}</ul><p>The app will re-query canonical state, then immediately revalidate the wallet chain and signer account. It stops if either changed.</p>{error&&<p className="action-error" role="alert">{error}</p>}<button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const value=await transactions.confirm(review);setReceipt(value);onSuccess(value)}catch(value){setError(value instanceof Error?value.message:'Transaction unavailable.')}finally{setBusy(false)}}}>{busy?'Checking & signing…':'Confirm in wallet'}</button> <button className="button" disabled={busy} onClick={onCancel}>Back</button></div>;
}
