import { SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import { GasPrice } from '@cosmjs/stargate';
import type { OfflineSigner } from '@cosmjs/proto-signing';
import { toUtf8 } from '@cosmjs/encoding';
import { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';
import type { AppConfig } from './config';
import type { ContractConfig, Request } from './types';

export interface Coin { denom: string; amount: string }
export interface SubmitInput { title: string; summary: string; acceptance_criteria: string; category: string; detail_uri: string; detail_digest: string }
export type PublicExecuteMessage = { submit_request: { title:string; summary:string; acceptance_criteria:string; category:string; detail_uri:string|null; detail_digest:string|null } } | { withdraw_refund: { request_id:number } };
export interface TransactionReview { kind:'submit'|'refund'; chainId:string; sender:string; contract:string; message:PublicExecuteMessage; funds:Coin[]; implications:string[]; fingerprint:string }
export interface TransactionSuccess { hash:string; explorerUrl:string; requestId:number }
export interface ExecuteResult { code:number; transactionHash:string; rawLog?:string; events?:readonly { type:string; attributes:readonly { key:string; value:string }[] }[] }
export interface SigningClient { execute(sender:string, contract:string, message:PublicExecuteMessage, fee:'auto', memo:string, funds:readonly Coin[]):Promise<ExecuteResult>; disconnect():void }

export interface WalletExtension { experimentalSuggestChain?(chain:ChainInfo):Promise<void>; enable(chainId:string):Promise<void>; getOfflineSigner(chainId:string):OfflineSigner; getChainId?():Promise<string> }
export interface ChainInfo { chainId:string; chainName:string; rpc:string; rest:string; bip44:{coinType:number}; bech32Config:Record<string,string>; currencies:readonly Currency[]; feeCurrencies:readonly Currency[]; stakeCurrency:Currency; features:readonly string[] }
interface Currency { coinDenom:string; coinMinimalDenom:string; coinDecimals:number; gasPriceStep?:{low:number;average:number;high:number} }
export interface WalletWindow extends Window { keplr?:WalletExtension; leap?:WalletExtension }
export interface LatestState { config():Promise<ContractConfig>; request(id:number):Promise<Request> }
export type SigningConnector = (rpc:string, signer:OfflineSigner)=>Promise<SigningClient>;

const utf8Length=(value:string)=>new TextEncoder().encode(value).length;
const stable=(value:unknown)=>JSON.stringify(value);
export function chainInfo(config:AppConfig):ChainInfo { const currency={coinDenom:'JUNOX',coinMinimalDenom:'ujunox',coinDecimals:6,gasPriceStep:{low:.025,average:.04,high:.075}}; return { chainId:config.chainId,chainName:'Juno Testnet (uni-7)',rpc:config.rpc,rest:'https://api.uni.junonetwork.io',bip44:{coinType:118},bech32Config:{bech32PrefixAccAddr:'juno',bech32PrefixAccPub:'junopub',bech32PrefixValAddr:'junovaloper',bech32PrefixValPub:'junovaloperpub',bech32PrefixConsAddr:'junovalcons',bech32PrefixConsPub:'junovalconspub'},currencies:[currency],feeCurrencies:[currency],stakeCurrency:currency,features:['cosmwasm']}; }

export class WalletConnection {
  private client:SigningClient|null=null; private extension:WalletExtension|null=null; private listeners=new Set<()=>void>();
  constructor(private config:AppConfig,private browser:WalletWindow=window as WalletWindow,private connectSigning:SigningConnector=async(rpc,signer)=>{const client=await SigningCosmWasmClient.connectWithSigner(rpc,signer,{gasPrice:GasPrice.fromString('0.04ujunox')});return {execute:(sender,contract,message,fee,memo,funds)=>client.signAndBroadcast(sender,[{typeUrl:'/cosmwasm.wasm.v1.MsgExecuteContract',value:MsgExecuteContract.fromPartial({sender,contract,msg:toUtf8(JSON.stringify(message)),funds:[...funds]})}],fee,memo),disconnect:()=>client.disconnect()};}){}
  account:string|null=null;
  async connect():Promise<string>{ this.disconnect(); const extension=this.browser.keplr??this.browser.leap; if(!extension) throw new Error('No compatible wallet found. Install or unlock Keplr or Leap.'); try { await extension.experimentalSuggestChain?.(chainInfo(this.config)); await extension.enable(this.config.chainId); const observed=await extension.getChainId?.(); if(observed&&observed!==this.config.chainId) throw new Error(`Wrong chain: wallet returned ${observed}; uni-7 is required.`); const signer=extension.getOfflineSigner(this.config.chainId); const accounts=await signer.getAccounts(); if(accounts.length!==1||!accounts[0].address.startsWith('juno1')) throw new Error('Wallet did not provide one valid Juno account.'); this.client=await this.connectSigning(this.config.rpc,signer); this.extension=extension; this.account=accounts[0].address; this.listen(); return this.account; } catch(error){this.disconnect();throw mapTransactionError(error)} }
  private listen(){ for(const name of ['keplr_keystorechange','leap_keystorechange','chainChanged']){ const callback=()=>{this.disconnect();for(const listener of this.listeners)listener();}; this.browser.addEventListener(name,callback,{once:true}); } }
  onChange(listener:()=>void){this.listeners.add(listener);return()=>{this.listeners.delete(listener)}}
  signingClient():SigningClient { if(!this.client||!this.account) throw new Error('Connect an unlocked wallet before continuing.'); return this.client; }
  disconnect(){this.client?.disconnect();this.client=null;this.extension=null;this.account=null;}
}

function validateText(value:string,max:number,label:string){if(!value.trim())throw new Error(`${label} is required.`);if(utf8Length(value)>max)throw new Error(`${label} exceeds the live ${max}-byte limit.`)}
export function buildSubmitReview(config:AppConfig,sender:string,live:ContractConfig,input:SubmitInput):TransactionReview { if(live.submissions_paused)throw new Error('Submissions are currently paused on chain.'); if(live.native_denom!=='ujunox')throw new Error('Unsupported live bond denomination.'); if(!/^\d+$/.test(live.submission_bond)||BigInt(live.submission_bond)<=0n)throw new Error('Invalid live submission bond.'); const limits=live.request_limits; validateText(input.title,limits.max_title_bytes,'Title');validateText(input.summary,limits.max_summary_bytes,'Summary');validateText(input.acceptance_criteria,limits.max_acceptance_criteria_bytes,'Acceptance criteria'); if(!/^[a-z0-9-]+$/.test(input.category)||utf8Length(input.category)>limits.max_category_bytes)throw new Error(`Category must use lowercase letters, digits, or hyphens within ${limits.max_category_bytes} bytes.`); const uri=input.detail_uri.trim(),digest=input.detail_digest.trim(); if(Boolean(uri)!==Boolean(digest))throw new Error('Detail URI and SHA-256 digest must be provided together.'); if(uri&&(!/^(https:\/\/|ipfs:\/\/).+/.test(uri)||utf8Length(uri)>limits.max_uri_bytes))throw new Error('Detail URI is invalid or exceeds the live byte limit.'); if(digest&&(!/^sha256:[0-9a-f]{64}$/.test(digest)||utf8Length(digest)>limits.max_digest_bytes))throw new Error('Detail digest must be sha256: followed by 64 lowercase hex characters.'); const message:PublicExecuteMessage={submit_request:{title:input.title,summary:input.summary,acceptance_criteria:input.acceptance_criteria,category:input.category,detail_uri:uri||null,detail_digest:digest||null}}; const funds=[{denom:live.native_denom,amount:live.submission_bond}]; const base={kind:'submit' as const,chainId:config.chainId,sender,contract:config.contract,message,funds,implications:['Creates a permanent public request.','The exact submission bond is locked and is refundable only if the contract later marks it refundable; spam bonds may be forfeited.']};return {...base,fingerprint:stable(base)}; }
export function refundEligible(request:Request,sender:string):boolean{return request.author===sender&&request.bond.state==='refundable'&&/^\d+$/.test(request.bond.amount)&&BigInt(request.bond.amount)>0n}
export function buildRefundReview(config:AppConfig,sender:string,request:Request):TransactionReview {if(!refundEligible(request,sender))throw new Error('Refund unavailable: only the author can withdraw a positive refundable bond.');const message:PublicExecuteMessage={withdraw_refund:{request_id:request.id}};const base={kind:'refund' as const,chainId:config.chainId,sender,contract:config.contract,message,funds:[] as Coin[],implications:[`Withdraws ${request.bond.amount} ujunox to the request author.`,'This claim is irreversible and changes the bond state to claimed.']};return {...base,fingerprint:stable(base)}}
function eventRequestId(result:ExecuteResult):number|null{for(const event of result.events??[])for(const attr of event.attributes)if(attr.key==='request_id'&&/^\d+$/.test(attr.value)){const id=Number(attr.value);if(Number.isSafeInteger(id)&&id>0)return id}return null}
export class PublicTransactions {constructor(private config:AppConfig,private latest:LatestState,private wallet:WalletConnection){}
  async reviewSubmit(input:SubmitInput){if(!this.wallet.account)throw new Error('Connect an unlocked wallet before continuing.');return buildSubmitReview(this.config,this.wallet.account,await this.latest.config(),input)}
  async reviewRefund(id:number){if(!this.wallet.account)throw new Error('Connect an unlocked wallet before continuing.');return buildRefundReview(this.config,this.wallet.account,await this.latest.request(id))}
  async confirm(review:TransactionReview):Promise<TransactionSuccess>{if(this.wallet.account!==review.sender)throw new Error('Wallet account changed. Review the transaction again.');let fresh:TransactionReview;if(review.kind==='submit'){if(!('submit_request'in review.message))throw new Error('Malformed reviewed submission.');const item=review.message.submit_request;fresh=buildSubmitReview(this.config,review.sender,await this.latest.config(),{...item,detail_uri:item.detail_uri??'',detail_digest:item.detail_digest??''});}else{if(!('withdraw_refund'in review.message))throw new Error('Malformed reviewed refund.');fresh=buildRefundReview(this.config,review.sender,await this.latest.request(review.message.withdraw_refund.request_id));}if(fresh.fingerprint!==review.fingerprint)throw new Error('On-chain state changed. Review the refreshed transaction before signing.');let result:ExecuteResult;try{result=await this.wallet.signingClient().execute(review.sender,review.contract,review.message,'auto','Juno Voice',review.funds)}catch(error){throw mapTransactionError(error)}if(result.code!==0)throw new Error(`Transaction failed with code ${result.code}${result.rawLog?`: ${result.rawLog}`:'.'}`);const requestId=review.kind==='refund'&&'withdraw_refund'in review.message?review.message.withdraw_refund.request_id:eventRequestId(result);if(requestId===null)throw new Error('Transaction succeeded but canonical request confirmation was unavailable. Refresh before retrying.');const canonical=await this.latest.request(requestId);if(review.kind==='submit'){if(!('submit_request'in review.message))throw new Error('Malformed reviewed submission.');const expected=review.message.submit_request;if(canonical.author!==review.sender||canonical.title!==expected.title||canonical.summary!==expected.summary||canonical.acceptance_criteria!==expected.acceptance_criteria||canonical.category!==expected.category||canonical.detail_uri!==expected.detail_uri||canonical.detail_digest!==expected.detail_digest)throw new Error('Transaction succeeded but the canonical request did not match the reviewed submission.');}else if(canonical.bond.state!=='claimed')throw new Error('Transaction succeeded but the canonical refund state is not yet confirmed.');return {hash:result.transactionHash,explorerUrl:`${this.config.explorer}/tx/${encodeURIComponent(result.transactionHash)}`,requestId}}
}
export function mapTransactionError(error:unknown):Error{const message=error instanceof Error?error.message:String(error);if(/reject|denied|cancel/i.test(message))return new Error('Wallet request rejected. No transaction was broadcast.');if(/lock/i.test(message))return new Error('Wallet is locked. Unlock it and try again.');if(/wrong chain|chain.*mismatch|unsupported chain/i.test(message))return new Error(`Wrong chain. Switch the wallet to uni-7. (${message})`);if(/insufficient funds/i.test(message))return new Error('Insufficient funds for the bond and network fee.');if(/timeout|network|fetch|rpc|socket/i.test(message))return new Error('Network or RPC failure. No success has been assumed.');return new Error(`Transaction unavailable: ${message}`)}
